### ISSUE TITLE
Fails to download files from resources.download.minecraft.net due to not using HTTPS

### ISSUE THREAD

**Issue by TheMCNerd2017** [Idumein/mcdl#1]
All assets from the `resources.download.minecraft.net` domain fail to download correctly, with all files downloaded being an HTML error document with the error code "AccountRequiresHttps". Loading one of the asset URLs in a web browser automatically upgrades the connection to HTTPS and allows you to download the asset. Changing part of line 71 in the `go.main` file to HTTPS seemed to fix the issue on my end however I have not completed a full asset download yet so I'm not sure if that fix causes other issues to come up.

**Comment by Idumein** [comment]
Fixed, thanks for reporting.
